# Generated by Django 4.0.1 on 2023-05-28 23:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.CharField(max_length=1000)),
                ('country', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=15)),
                ('image', models.ImageField(blank=True, default='blank-profile-picture.png', null=True, upload_to='profile/')),
                ('experiance1', models.CharField(max_length=100)),
                ('experiance2', models.CharField(max_length=100)),
                ('cv', models.FileField(default='Course_Certificate_En_Database_Fundamentals.pdf', upload_to='cvProfile/')),
                ('githublink', models.URLField(db_index=True, max_length=150, null=True, unique=True)),
                ('linkedinlink', models.URLField(db_index=True, max_length=150, null=True, unique=True)),
                ('nationality', models.CharField(max_length=100)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(max_length=50)),
                ('typejop', models.CharField(max_length=100)),
                ('categories', models.CharField(max_length=100)),
                ('salary', models.IntegerField(default=4000)),
                ('experianceyears', models.CharField(max_length=50)),
                ('leveleducation', models.CharField(max_length=100)),
                ('faculty', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('graduationyear', models.CharField(max_length=100)),
                ('languages', models.CharField(max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
