# Generated by Django 4.0.1 on 2023-07-08 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_rename_graduationyear_profile_educationallevel_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='educationallevel',
            new_name='edulevel',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='experiance1',
            new_name='expyears',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='experiance2',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='gradYear',
            new_name='graduationyear',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='typejop',
            new_name='last_name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='experianceyears',
        ),
        migrations.AddField(
            model_name='profile',
            name='typejob',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='profile/'),
        ),
    ]
