# Generated by Django 4.0.1 on 2023-07-12 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_rename_educationallevel_profile_edulevel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='githublink',
            field=models.URLField(db_index=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='linkedinlink',
            field=models.URLField(db_index=True, max_length=150, null=True),
        ),
    ]
