# Generated by Django 4.0.1 on 2023-06-18 18:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Jop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('place', models.CharField(choices=[('Menofia', 'Menofia'), ('Cairo', 'Cairo'), ('Giza', 'Giza'), ('Tanta', 'Tanta'), ('Mansora', 'Mansora'), ('Kafr Elshek', 'Kafr Elshek'), ('6 Octper', '6 Octper')], max_length=20)),
                ('Jop_Type', models.CharField(choices=[('Full Time', 'Full Time'), ('Part Time', 'Part Time')], max_length=15)),
                ('Description', models.TextField(max_length=1000)),
                ('Published_at', models.DateTimeField(auto_now=True)),
                ('Vacancy', models.IntegerField(default=1)),
                ('Salary', models.IntegerField(default=0)),
                ('Experiance', models.IntegerField(default=1)),
                ('image', models.ImageField(blank=True, default='blank-profile-picture.png', null=True, upload_to='job/')),
                ('slug', models.SlugField(blank=True, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jop_owner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
