# Generated by Django 4.0.1 on 2023-06-18 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jop',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
