# Generated by Django 4.0.1 on 2023-07-12 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_apply_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apply',
            old_name='creted_at',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='apply',
            name='job_owner',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='apply',
            name='job_title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='apply',
            name='made_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='comments',
            name='username',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
