# Generated by Django 4.0.1 on 2023-07-03 21:21

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('job', '0003_alter_jop_description_alter_jop_experiance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jop',
            name='Published_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 7, 4, 0, 21, 33, 570570), null=True),
        ),
        migrations.CreateModel(
            name='Apply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creted_at', models.DateTimeField(auto_now=True)),
                ('jop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apply_jop', to='job.jop')),
                ('name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_apply_jop', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
